name: Auto Assign to Project(s)

on:
  issues:
#     types: [opened, labeled]
    types: [labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
#     - name: Assign NEW issues
#       uses: srggrs/assign-one-project-github-action@1.2.0
#       if: github.event.action == 'opened'
#       with:
#         project: 'https://github.com/srggrs/assign-one-project-github-action/projects/2'

    - name: Assign issues and pull requests with `roadmap` label to project 4
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: contains(github.event.issue.labels.*.name, 'roadmap')
      with:
        project: 'https://github.com/rubengarciam/wayne/projects/4'
        column_name: 'In Review'
